### ISSUE TITLE
help!!!!!!!

### ISSUE THREAD

**Issue by wangjian1119** [nkalinov/ng2-datetime#161]
hello ,i'm student,      ng2-datetime   how to do with angular/cli                emergency！！！！！

thank you

**Comment by wangjian1119** [comment]
i use ng2-admin ,  This project from webpack to cli

**Comment by wartab** [comment]
Don't do your homework late. What is the issue you are having?

**Comment by wangjian1119** [comment]
@wartab  hello , 

Those dependencies are imported by webpack in this project. But now ng2-admin has no use of webpack, using angular2 cli.So the problem is, how to import these dependencies with cli

thanks

**Comment by wartab** [comment]
I do not know ng2-admin and the fact that I don't understand what you need to do doesn't really help either.

What happens when you try to follow the procedure that is written in the README? As far as I know, there should be no difference. Any error message? Did you even try?

**Comment by wangjian1119** [comment]
@wartab thank you

**Comment by rajeshkamthe** [comment]
Using ng2-datetime with angular-cli
1. npm install --save ng2-datetime
2. Include styles & scripts into angular-cli.json file as shown

>       "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.css",
        "../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap-datepicker/js/bootstrap-datepicker.js",
        "../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"
      ],

3. import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';

> Add it to your app module's imports property

@NgModule({
    ...
    imports: [NKDatetimeModule, ...],
    ...
})

3. import $ into the module as 

> import * as $ from 'jquery';

4. Consume it into the template
> <datetime [(ngModel)]="date"></datetime>

**Comment by wangjian1119** [comment]
@rajeshkamthe  That's right，Thank you very much.

**Comment by bandman0226** [comment]
@rajeshkamthe After following your instructions I still get 

ERROR in F:/test/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts (176,27): Cannot find name 'jQuery'.

ERROR in F:/test/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts (197,27): Cannot find name 'jQuery'.

ERROR in F:/test/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts (176,27): Cannot find name 'jQuery'.

ERROR in F:/test/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts (197,27): Cannot find name 'jQuery'.

Any ideas what might be causing this?

**Comment by wartab** [comment]
Run `npm install --save-dev @types/jquery`

**Comment by bandman0226** [comment]
Thank You @wartab ! That worked!

**Comment by seza443** [comment]
What really helped me was to add

`import * as $ from 'jquery';` into *app.module.ts*

**Comment by syarifuddinahmads** [comment]
@seza443 , thanks very much, really work for me

**Comment by agustinaliagac** [comment]
Thanks @rajeshkamthe . I still had to add "bootstrap timepicker"s JS like so:

```
"scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap-datepicker/js/bootstrap-datepicker.js",
        "../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"
      ],
```

Otherwise the time picker won't show up

**Comment by venkatesh-chinni** [comment]
Followed @rajeshkamthe comment. Getting this error 

no such file or directory, open 'C:\Users\chinn\OneDrive\Desktop\Nova\node_modules\jquery\dist\jquery.js'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Storage.provideSync (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@ngtools\webpack\src\compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:54)
    at Promise (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at hook (C:\Users\chinn\OneDrive\Desktop\Nova\FrontEndApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:67:43)
