### ISSUE TITLE
No provider for NgControl!

### ISSUE THREAD

**Issue by sumitarora** [nkalinov/ng2-datetime#54]
I am trying to configure datetime in my application but it keeps failing due to below error. Link to repo I am trying in https://github.com/sumitarora/angular2-examples
```
VM27654:46EXCEPTION: Uncaught (in promise): Error: Error in ./RioHelloPageComponent class RioHelloPageComponent - inline template:1:4 caused by: No provider for NgControl!
ErrorHandler.handleError @ VM27654:46
next @ VM27653:298
schedulerFn @ VM27680:89
SafeSubscriber.__tryOrUnsub @ VM27685:223
SafeSubscriber.next @ VM27685:172
Subscriber._next @ VM27685:125
Subscriber.next @ VM27685:89
Subject.next @ VM27681:55
EventEmitter.emit @ VM27680:81
onHandleError @ VM27698:65
Zone.runGuarded @ zone.js?fad3:113
_loop_1 @ zone.js?fad3:379
drainMicroTaskQueue @ zone.js?fad3:386
VM27654:51ORIGINAL STACKTRACE:
ErrorHandler.handleError @ VM27654:51
next @ VM27653:298
schedulerFn @ VM27680:89
SafeSubscriber.__tryOrUnsub @ VM27685:223
SafeSubscriber.next @ VM27685:172
Subscriber._next @ VM27685:125
Subscriber.next @ VM27685:89
Subject.next @ VM27681:55
EventEmitter.emit @ VM27680:81
onHandleError @ VM27698:65
Zone.runGuarded @ zone.js?fad3:113
_loop_1 @ zone.js?fad3:379
drainMicroTaskQueue @ zone.js?fad3:386
VM27654:52Error: Uncaught (in promise): Error: Error in ./RioHelloPageComponent class RioHelloPageComponent - inline template:1:4 caused by: No provider for NgControl!
    at resolvePromise (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:429:31)
    at eval (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:406:13)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:7790:1), <anonymous>:44:37)
    at Zone.run (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:96:43)
    at eval (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:462:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:236:37)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:7790:1), <anonymous>:35:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:235:42)
    at Zone.runTask (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:136:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8080/app.43b6a97f05d0553786db.js:9817:1), <anonymous>:368:35)

```

**Comment by sumitarora** [comment]
Got it working 😄

**Comment by DominicSachs** [comment]
What was your solution?
